### ISSUE TITLE
Implement multilingual support for course content

### ISSUE THREAD

**Issue by entelecheia** [entelecheia/course-template#18]
## Description:

Our course-template project currently supports only a single language. To make our course materials more accessible to a global audience, we should implement multilingual support using Jupyter Book's internationalization features. This issue outlines the specific steps to achieve this goal.

## Tasks:

1. Update `_config.yml` in the `docs/` folder to include the following settings:

```yaml
sphinx:
  config:
    language: en # Define the source language
    html_search_language: en # Adjust as needed for better search parsing
    # i18n related settings
    nb_render_priority:
      gettext: {}
    locale_dirs: ["locale/"]
    gettext_compact: false
    gettext_additional_targets: ["literal-block"]
    gettext_location: false
```

2. Generate gettext files (translation templates):

   ```
   jupyter book build --builder custom --custom-builder gettext docs
   ```

3. Create .po files for the target language:

   ```
   sphinx-intl update -p docs/_build/gettext -d docs/locale -l [target_language]
   ```

   Replace [target_language] with the desired language code (e.g., 'es' for Spanish, 'ko' for Korean).

4. Translate the content in the generated .po files.

5. Build the HTML files for the source language:

   ```
   jupyter book build docs
   ```

6. Generate HTML files for the target language:

   ```
   jupyter book config sphinx docs
   sphinx-build -b html -D language=[target_language] docs [path_for_translated_htmls]
   ```

   Replace [target_language] and [path_for_translated_htmls] as appropriate.

7. Implement a language switcher in the book's HTML template.

8. Update build scripts or GitHub Actions to automate the multilingual build process.

9. Update project documentation to explain the multilingual structure and how to add new languages.

10. Test the multilingual setup thoroughly, ensuring all languages render correctly and the language switcher works as expected.

## Additional Considerations:

- Decide on a directory structure for multilingual content (e.g., `docs/en/`, `docs/es/`, etc.)
- Ensure the table of contents (`_toc.yml`) is properly structured for each language.
- Consider using a translation management tool to streamline the translation process for larger projects.

This enhancement will significantly increase the accessibility of our course materials, making them available to a broader, global audience.
